"""conversation_messages

Revision ID: bf189284837e
Revises: f85cefec92d4
Create Date: 2026-09-29 09:24:12.325935
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'bf189284837e'
down_revision: Union[str, Sequence[str], None] = 'f85cefec92d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ticket_id', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=24), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_ticket_id'), 'conversation_messages', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_messages_ticket_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    # ### end Alembic commands ###
