"""unique_active_policy

Revision ID: f85cefec92d4
Revises: 618f2fbc13f7
Create Date: 2026-09-29 09:20:07.189049
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f85cefec92d4'
down_revision: Union[str, Sequence[str], None] = '618f2fbc13f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_active_policy', 'policy_bundles', ['active'], unique=True, sqlite_where=sa.text('active IS 1'), postgresql_where=sa.text('active IS 1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_policy', table_name='policy_bundles', sqlite_where=sa.text('active IS 1'), postgresql_where=sa.text('active IS 1'))
    # ### end Alembic commands ###
